### ISSUE TITLE
need tests

### ISSUE THREAD

**Issue by riveramj** [hacklanta/hubot-yardmaster#5]
def need some tests

**Comment by arigoldx** [comment]
tried to run the test in branch `testing-1-2-3` but after an `npm install` i'm gettin':

```
~/src/hubot-yardmaster [testing-1-2-3] $ npm test

> hubot-yardmaster@1.0.28 test /Users/arigold/src/hubot-yardmaster
> mocha --compilers coffee:coffee-script/register tests

/Users/arigold/src/hubot-yardmaster/tests/yardmaster-test.coffee:45
          return function*() {
                         ^
SyntaxError: Unexpected token *
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.loadFile (/Users/arigold/src/hubot-yardmaster/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/arigold/src/hubot-yardmaster/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /Users/arigold/src/hubot-yardmaster/node_modules/mocha/lib/mocha.js:219:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/arigold/src/hubot-yardmaster/node_modules/mocha/lib/mocha.js:216:14)
  at Mocha.run (/Users/arigold/src/hubot-yardmaster/node_modules/mocha/lib/mocha.js:468:10)
  at Object.<anonymous> (/Users/arigold/src/hubot-yardmaster/node_modules/mocha/bin/_mocha:403:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

npm ERR! Test failed.  See above for more details.
```

i'll keep on keepin on but thought i'd post.. been :eyes: and it could be a node version issue. here's mine:

```
~/src/hubot-yardmaster [testing-1-2-3] $ node --version
v0.12.7
```

HMM
